#!/bin/bash
#PBS -N WGANScriptCondaE3restart
#PBS -q gpu_1
#PBS -l select=1:ncpus=9:ngpus=1
#PBS -P CSCI1142
#PBS -l walltime=2:00:00
#PBS -o /mnt/lustre/users/schetty1/WGANRuns/Condarun1E3restart.out
#PBS -e /mnt/lustre/users/schetty1/WGANRuns/Condarun1E3restart.err
#PBS -m abe
#PBS -M chtsha042@myuct.ac.za
cd /home/schetty1/ 
module load chpc/python/anaconda/3-2021.11
eval "$(conda shell.bash hook)"
conda activate /mnt/lustre/users/schetty1/CondaGAN
module load chpc/cuda/11.6/PCIe/11.6 
python3 /home/schetty1/WGANGP.py --lr=0.001 --experiment=E3 --dataset=Elbow --img_size=256 --continueTraining --restartFile=/mnt/lustre/users/schetty1/GeneratedImages/WGANGP/Elbow/models/modelsE3/model-183.pt
conda deactivate
