'''
A python script to take the images generated by Vanilla GAN and WGANGP and split it into subfolders based on its training iteration
'''
print("S")
import os
import shutil

# Define the source folder containing your images
folders = ["/mnt/lustre/users/schetty1/GeneratedImages/WGANGP/Elbow/E1"]
for source_folder in folders:
    image_paths = {}

    # Iterate through the files in the source folder
    for filename in os.listdir(source_folder):
        # Get the truncated filename (excluding the last letter)
        truncated_name = filename[:-5]
        print(truncated_name)
        
        # Create a list of image paths with the same truncated name
        if truncated_name in image_paths:
            image_paths[truncated_name].append(os.path.join(source_folder, filename))
        else:
            image_paths[truncated_name] = [os.path.join(source_folder, filename)]

    # Create subfolders and move images
    for truncated_name, paths in image_paths.items():
        # Create a subfolder with the truncated name
        subfolder_path = os.path.join(source_folder, truncated_name)
        print(subfolder_path)
        os.makedirs(subfolder_path, exist_ok=True)
        
        for path in paths:
            shutil.move(path, os.path.join(subfolder_path, os.path.basename(path)))

    print("Images have been split into subfolders based on their names (excluding the last letter).")
